name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"  # once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate animation
        uses: cedric-f/github-contribution-grid-pacman@main
        with:
          github_user_name: sino-datagenius
          squares_color: "#2fc2b4"
          background_color: "#000000"
          animation_duration: 4

      - name: push animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
